#!/usr/bin/env bash
#
# d2-gateway.sh -- run the intent gateway for an evidence session.
#
#   ./scripts/d2-gateway.sh start   boot it, capture its pino NDJSON as evidence
#   ./scripts/d2-gateway.sh stop    shut it down
#   ./scripts/d2-gateway.sh status  is it up, and against which contract
#
# The gateway's pino log IS the SOW 6.1 D2 transcript, so stdout is appended
# verbatim to evidence/d2-gateway.ndjson and NOTHING is allowed to interleave
# with it: stderr goes to its own file, because one non-JSON line in the middle
# of the transcript breaks every reviewer tool that reads it line by line.
#
# ---------------------------------------------------------------------------
# One environment override, and why it is here
# ---------------------------------------------------------------------------
# HISTORICAL: when this evidence run was made, apps/gateway/registry.json still
# pinned network.contract_id to the pre-redeploy contract while .env,
# services.json and apps/console/.env pointed at the current one, and
# Registry.load() refused to boot on that mismatch -- correctly, it is exactly
# the misconfiguration that check exists to catch. The registry has since been
# corrected, so the override below is now a no-op. It is kept so the run stays
# reproducible exactly as it was recorded.
#
# Editing apps/** is out of scope for this evidence run, so this script writes a
# corrected COPY to evidence/d2-gateway-registry.effective.json (the committed
# file, with network.contract_id replaced by $CONTRACT_ID and nothing else) and
# points the gateway at it with GATEWAY_REGISTRY_PATH. The copy is kept as
# evidence so a reviewer can diff it against the committed file and see that the
# agent and asset tables are untouched.
#
# The real fix belongs in apps/gateway/registry.json.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

EVIDENCE_DIR="${EVIDENCE_DIR:-$REPO_ROOT/evidence}"
NDJSON="$EVIDENCE_DIR/d2-gateway.ndjson"
STDERR_LOG="$EVIDENCE_DIR/d2-gateway.stderr.log"
EFFECTIVE_REGISTRY="$EVIDENCE_DIR/d2-gateway-registry.effective.json"
PID_FILE="$REPO_ROOT/.d2-gateway.pid"

mkdir -p "$EVIDENCE_DIR"

# .env is deliberately NOT sourced.
#
# AGENT_SECRETS holds unquoted JSON, and `set -a; . .env` strips its inner
# double quotes, so the gateway would receive `{GAUU…:SBLG…}` and refuse to boot
# with "AGENT_SECRETS must be a JSON object". The gateway (and the executor) load
# .env themselves through Node's process.loadEnvFile, which parses it correctly.
# This script therefore reads only the two plain scalars it needs for its own
# bookkeeping, and never exports anything from that file.
env_value() { sed -n "s/^$1=//p" "$REPO_ROOT/.env" | head -1 | tr -d '"'; }

CONTRACT_ID="${CONTRACT_ID:-$(env_value CONTRACT_ID)}"
PORT="${PORT:-$(env_value PORT)}"
GATEWAY_URL="http://127.0.0.1:${PORT:-8080}"

write_effective_registry() {
  python3 - "$REPO_ROOT/apps/gateway/registry.json" "$EFFECTIVE_REGISTRY" "$CONTRACT_ID" <<'PY'
import json, sys
src, dst, contract_id = sys.argv[1], sys.argv[2], sys.argv[3]
with open(src, encoding="utf-8") as fh:
    reg = json.load(fh)
committed = reg["network"]["contract_id"]
if committed == contract_id:
    print(f"  registry.json already pins {contract_id}; the copy is a verbatim one")
else:
    print(f"  registry.json pins {committed}, CONTRACT_ID is {contract_id} -- overriding network.contract_id only")
reg["network"]["contract_id"] = contract_id
reg["_effective_copy_note"] = (
    "Generated by scripts/d2-gateway.sh from apps/gateway/registry.json. The ONLY field "
    "changed is network.contract_id, which the committed file still pins to the "
    f"pre-redeploy contract {committed}. Agents, assets and every other value are verbatim."
)
with open(dst, "w", encoding="utf-8") as fh:
    json.dump(reg, fh, indent=2)
    fh.write("\n")
PY
}

case "${1:-}" in
  start)
    if [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
      echo "gateway already running (pid $(cat "$PID_FILE"))"
      exit 0
    fi
    echo "== effective registry"
    write_effective_registry
    echo "== starting gateway on $GATEWAY_URL against $CONTRACT_ID"
    GATEWAY_REGISTRY_PATH="$EFFECTIVE_REGISTRY" \
      npx tsx "$REPO_ROOT/apps/gateway/src/server.ts" >>"$NDJSON" 2>>"$STDERR_LOG" &
    echo $! >"$PID_FILE"
    for _ in $(seq 1 60); do
      if curl -fsS "$GATEWAY_URL/health" >/dev/null 2>&1; then
        echo "  healthy after $SECONDS s"
        curl -fsS "$GATEWAY_URL/health" | python3 -m json.tool
        exit 0
      fi
      sleep 1
    done
    echo "gateway did not become healthy; last stderr:" >&2
    tail -20 "$STDERR_LOG" >&2
    exit 1
    ;;
  stop)
    if [[ -f "$PID_FILE" ]]; then
      pid="$(cat "$PID_FILE")"
      kill "$pid" 2>/dev/null || true
      # tsx spawns a child; take the whole group down if it is still listening.
      sleep 2
      pkill -f "tsx .*apps/gateway/src/server.ts" 2>/dev/null || true
      rm -f "$PID_FILE"
      echo "gateway stopped (pid $pid)"
    else
      pkill -f "tsx .*apps/gateway/src/server.ts" 2>/dev/null || true
      echo "no pid file; killed any stray gateway process"
    fi
    ;;
  status)
    curl -fsS "$GATEWAY_URL/health" | python3 -m json.tool || echo "gateway is not answering on $GATEWAY_URL"
    ;;
  *)
    echo "usage: $0 {start|stop|status}" >&2
    exit 2
    ;;
esac
